GET https://tcc-be-836058602525.asia-southeast2.run.app/notes

###
GET http://localhost:5000/notes/1

###
POST http://localhost:5000/notes
Content-Type: application/json

{
    "judul": "John Doe",
    "konten": "john@gmail.com"
}

###
PATCH http://localhost:5000/notes/1
Content-Type: application/json

{
    "judul": "M Fikri",
    "konten": "mfikri@gmail.com"
}

###
DELETE http://localhost:5000/notes/2

###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiam9obmRvZSIsImVtYWlsIjoiMTIzIiwiaWF0IjoxNzQ3NDczNzkwLCJleHAiOjE3NDc0NzM4MTB9.XpeqFQeam7ELHVYhxHcJ-CuNvsKhEugZP4BD8EpIvRI

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "johndoe",
    "email": "123",
    "password": "password123",
    "confPassword": "password123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "123",
    "password": "password123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
